[package]
name = "skip-a-herz"
description = "project that explores the just noticeable difference (JND) in human perception of time gaps between tones"
categories = ["embedded"]
keywords = ["audio"]
authors = ["crjeder <crjeder@gmail.com>"]
repository = "https://github.com/crjeder/hx711_spi"
readme = "README.md"
documentation = "https://docs.rs/hx711_spi"
license = "MIT OR Apache-2.0"
edition = "2021"
version = "0.0.1"
include = ["src/main.rs", "LICENSE", "README.md", "CHANGELOG.md"]

[future-incompat-report]
frequency = "always"

[dependencies]
rp-pico = "0.9"
embedded-hal = "1.0.0"
rand = { version = "0.8", default-features = false }

[features]
default = ["rp-pico/rt"]
